services:
  pg:
    container_name: pg_sql
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=yasl
      - POSTGRES_PASSWORD=yaslPass01
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 54322:5432
  
volumes:
  pgdata: